parameters:
    ezpublish.fieldType.ezpage.parameterProvider.class: eZ\Publish\Core\MVC\Symfony\FieldType\Page\ParameterProvider
    ezpublish.fieldType.ezpage.pageService.class: EzSystems\EzPlatformPageFieldTypeBundle\FieldType\Page\PageService
    ezpublish.fieldType.ezpage.pageService.factory.class: eZ\Publish\Core\MVC\Symfony\FieldType\Page\PageServiceFactory
    ezpublish.fieldType.ezpage.block.class: eZ\Publish\Core\FieldType\Page\Parts\Block
    ezpublish.fieldType.ezpage.zone.class: eZ\Publish\Core\FieldType\Page\Parts\Zone
    ezpublish.fieldType.ezpage.hashConverter.class: eZ\Publish\Core\FieldType\Page\HashConverter

services:
    ezpublish.fieldType.ezpage.parameterProvider:
        class: %ezpublish.fieldType.ezpage.parameterProvider.class%
        arguments: [@ezpublish.fieldType.ezpage.pageService]
        tags:
            - {name: ezpublish.fieldType.parameterProvider, alias: ezpage}

    ezpublish.fieldType.ezpage.pageService.factory:
        class: %ezpublish.fieldType.ezpage.pageService.factory.class%

    ezpublish.fieldType.ezpage.pageService:
        class: %ezpublish.fieldType.ezpage.pageService.class%
        factory: ["@ezpublish.fieldType.ezpage.pageService.factory", buildService]
        arguments:
            - %ezpublish.fieldType.ezpage.pageService.class%
            - @ezpublish.config.resolver
            - @ezpublish.fieldType.ezpage.storage_gateway
            - @ezpublish.api.service.content
        lazy: true

    ezpublish.fieldType.ezpage.hashConverter:
        class: %ezpublish.fieldType.ezpage.hashConverter.class%
