parameters:
    # Kernel related params
    #controller_resolver.class: eZ\Publish\MVC\Controller\Resolver
    webroot_dir: %kernel.root_dir%/../web

services:
    #controller_resolver:
    #    class: %controller_resolver.class%
    #    arguments: [@service_container]

