parameters:
    ezpublish.controller.page.view.class: EzSystems\EzPlatformPageFieldTypeBundle\Controller\PageController
    ezpublish_rest.field_type_processor.ezpage.class: eZ\Publish\Core\REST\Common\FieldTypeProcessor\PageProcessor

services:
    ezpublish.controller.page.view:
        class: %ezpublish.controller.page.view.class%
        arguments: [@ezpublish.view_manager, @ezpublish.fieldType.ezpage.pageService]
        parent: ezpublish.controller.base
        scope: request

    # This alias allows easier management for subrequests
    # Same as above for the page controller
    # {{ render( controller( "ez_page:viewAction", {'block': myBlock} ) ) }}
    ez_page:
        alias: ezpublish.controller.page.view

    ezpublish_rest.field_type_processor.ezpage:
        class: %ezpublish_rest.field_type_processor.ezpage.class%
        tags:
            - {name: ezpublish_rest.field_type_processor, alias: ezpage}
