parameters:
    # Kernel related params
    webroot_dir: %kernel.root_dir%/../web

    ezpublish.siteaccess.class: eZ\Bundle\EzPublishCoreBundle\SiteAccess
    ezpublish.controller.base.class: eZ\Publish\MVC\Controller\Controller
    ezpublish.controller.content.view.class: eZ\Publish\MVC\Controller\Content\ViewController
    ezpublish.controller.content.view.options: {}

services:
    # Siteaccess is injected in the container at runtime
    ezpublish.siteaccess:
        class: %ezpublish.siteaccess.class%

    ezpublish.controller.base:
        class: %ezpublish.controller.base.class%
        abstract: true
        calls:
            - [ setContainer, [@service_container] ]

    ezpublish.controller.content.view:
        class: %ezpublish.controller.content.view.class%
        arguments: [@ezpublish.view_manager, %ezpublish.controller.content.view.options%]
        parent: ezpublish.controller.base
        scope: request

    # This alias allows easier management for subrequests
    # {% render "ez_content:viewLocation" with {"locationId": 123, "viewMode": "line"} %}
    ez_content:
        alias: ezpublish.controller.content.view
