parameters:
    ezpublish.twig.extension.content.class: eZ\Publish\MVC\Templating\Twig\Extension\ContentExtension
    ezpublish.twig.content_helper.resources: [content_fields_full.html.twig]

services:
    ezpublish.twig.extension.content:
        class: %ezpublish.twig.extension.content.class%
        arguments: [%ezpublish.twig.content_helper.resources%]
        public: false
        tags:
            - {name: twig.extension}
