parameters:
    ezpublish.twig.extension.content.class: eZ\Publish\MVC\Templating\Twig\Extension\ContentExtension
    ezpublish.twig.content_helper.resources: [content_fields.html.twig]

    ezpublish.view_manager.class: eZ\Publish\MVC\View\Manager

services:
    ezpublish.twig.extension.content:
        class: %ezpublish.twig.extension.content.class%
        arguments: [%ezpublish.twig.content_helper.resources%]
        public: false
        tags:
            - {name: twig.extension}

    ezpublish.view_manager:
        class: %ezpublish.view_manager.class%
        arguments: [@templating, @?logger]
