parameters:
    # Twig related params
    twig.class: Twig_Environment
    twig.loader.class: Twig_Loader_Filesystem
    twig.engine.class: eZ\Publish\MVC\Template\Twig\Engine
    twig.options:
        cache: %kernel.cache_dir%/twig

    # Base directory for templates
    # This is temporary since bundles might also provide templates
    templating.base_dir: %kernel.root_dir%/Resources/views

services:
    twig:
        class: %twig.class%
        arguments: [@twig.loader, %twig.options%]
        public: false

    twig.loader:
        class: %twig.loader.class%
        arguments: [%templating.base_dir%]
        public: false

    templating.engine.twig:
        class: %twig.engine.class%
        arguments: [@twig]
        public: false

    ezpublish.templating:
        alias: templating.engine.twig
