parameters:
    ezpublish.block_view.matcher_factory.class: EzSystems\EzPlatformPageFieldTypeBundle\Matcher\BlockMatcherFactory
    ezpublish.view_provider.configured.class: eZ\Bundle\EzPublishCoreBundle\View\Provider\Configured
    ezpublish.view.block_cache_response_listener.class: EzSystems\EzPlatformPageFieldTypeBundle\EventListener\BlockCacheResponseListener
    ezpublish.view.view_parameters.injector.block.valid_items.class: eZ\Publish\Core\MVC\Symfony\View\ParametersInjector\Block\ValidItems
    ezpublish.view.view_parameters.injector.block.valid_content_info_items.class: EzSystems\EzPlatformPageFieldTypeBundle\EventListener\BlockValidContentInfoItemsListener
    ezpublish.view_builder.block.class: eZ\Publish\Core\MVC\Symfony\View\Builder\BlockViewBuilder

services:
    ezpublish.block_view_provider.configured:
        class: %ezpublish.view_provider.configured.class%
        arguments: [@ezpublish.block_view.matcher_factory]
        tags:
            - {name: ezpublish.view_provider, type: 'eZ\Publish\Core\MVC\Symfony\View\BlockView', priority: 10}

    ezpublish.block_view.matcher_factory:
        class: %ezpublish.block_view.matcher_factory.class%
        arguments: [@ezpublish.config.resolver, @ezpublish.api.repository]
        calls:
            - [setContainer, [@service_container]]

    # Injected to ezpublish.view_builder.registry through compiler pass
    ezpublish.view_builder.block:
        class: %ezpublish.view_builder.block.class%
        arguments:
            - @ezpublish.fieldType.ezpage.pageService
            - @ezpublish.view.configurator
            - @ezpublish.view.view_parameters.injector.dispatcher

    ezpublish.view.view_parameters.injector.block.valid_items:
        class: %ezpublish.view.view_parameters.injector.block.valid_items.class%
        arguments: [@ezpublish.fieldType.ezpage.pageService]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.view.view_parameters.injector.block.valid_content_info_items:
        class: %ezpublish.view.view_parameters.injector.block.valid_content_info_items.class%
        arguments: [@ezpublish.fieldType.ezpage.pageService]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.view.block_cache_response_listener:
        class: %ezpublish.view.block_cache_response_listener.class%
        calls:
            - [setEnableViewCache, [$content.view_cache$]]
        tags:
            - { name: kernel.event_subscriber }
